---
title: "final"
author: "Q"
date: "2023-07-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(fpp2)
library(rmarkdown)
library(itsmr)
library(readr)
```

```{r}
spx.y5<-read_csv("process/SPX_5years.csv")
spx.y2<-read_csv("process/SPX_2years.csv")
spx.y3<-read_csv("process/SPX_3years.csv")
spx.f7<-read_csv("process/SPX_freq7.csv")
spx.f7m<-read_csv("process/SPX_freq7_mean.csv")
spx.f30<-read_csv("process/SPX_freq30.csv")
na<-read_csv("data/NASDAQ.csv")
dji<-read_csv("data/DJIA.csv")
spx<-read_csv("data/SPX.csv")
```
```{r}
data<-spx.f5
```

```{r}
data.ts<-ts(data[,"Close"])
data.log<-ts(log(data[,"Close"]))
data.diff<-diff(data.ts)
data.logd<-diff(data.log)
```


```{r}
test(data.ts)
test(data.diff)
test(data.log)
test(data.logd)
data_mean<-mean(data.logd)
data_var<-var(data.logd)
```
```{r}
data_mean

data_var
```


```{r}
len<-length(data.log)
t<-floor(len*0.8)
myts <- ts(data.log)
myts.train <- window(myts,end=t)
myts.test <- window(myts,start=t+1)

fc <- auto.arima(myts.train)
future <- forecast::forecast(fc, h=(len-t))

autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(myts.test, series="Test")

autoplot(future)

p <- autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(future, series="Forecast")

p + autolayer(myts.test, series="Test")

checkresiduals(fc)
accuracy(future,myts.test)
```







