---
title: "finalproject"
date: "2023-07-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

#following code use R and the data from code_1 to generate plot
```{r}
library(fpp2)
library(rmarkdown)
library(itsmr)
library(readr)
```

```{r}
na<-read_csv("data/NASDAQ.csv")
dji<-read_csv("data/DJIA.csv")
spx<-read_csv("data/SPX.csv")
```

```{r}
dji.ts<-ts(dji[,"Close"])
na.ts<-ts(na[,"Close"])
spx.ts<-ts(spx[,"Close"])

na.log<-ts(log(na[,"Close"]))
dji.log<-ts(log(dji[,"Close"]))
spx.log<-ts(log(spx[,"Close"]))

na.diff<-diff(na.ts)
dji.diff<-diff(dji.ts)
spx.diff<-diff(spx.ts)

na.logd<-diff(na.log)
dji.logd<-diff(dji.log)
spx.logd<-diff(spx.log)

```
```{r}
test(na.ts)
test(na.diff)
test(na.log)
test(na.logd)
```
```{r}
test(dji.ts)
test(dji.diff)
test(dji.log)
test(dji.logd)
```
```{r}
test(spx.ts)
test(spx.diff)
test(spx.log)
test(spx.logd)
```




```{r}
myts <- ts(na.log, frequency=30)
myts.train <- window(myts,end=150)
myts.test <- window(myts,start=150)

autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(myts.test, series="Test")

fc <- auto.arima(myts.train)
future <- forecast::forecast(fc, h=20)
autoplot(future,h=100,include = 100)
checkresiduals(fc)
accuracy(future,myts.test)
```
```{r}
myts <- ts(dji.log, frequency=30)
myts.train <- window(myts,end=150)
myts.test <- window(myts,start=150)

autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(myts.test, series="Test")

fc <- auto.arima(myts.train)
future <- forecast::forecast(fc, h=20)
autoplot(future,h=100,include = 100)
checkresiduals(fc)
accuracy(future,myts.test)
```
```{r}
myts <- ts(spx.log, frequency=30)
myts.train <- window(myts,end=150)
myts.test <- window(myts,start=150)

autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(myts.test, series="Test")

fc <- auto.arima(myts.train)
future <- forecast::forecast(fc, h=20)
autoplot(future,h=100,include = 100)
checkresiduals(fc)
accuracy(future,myts.test)
```





ets
```{r}
myts <- ts(na.log, frequency=30)
myts.train <- window(myts,end=150)
myts.test <- window(myts,start=150)

autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(myts.test, series="Test")

fc <- ets(myts.train)
future <- forecast::forecast(fc, h=20)
autoplot(future,h=100,include = 100)
checkresiduals(fc)
accuracy(future,myts.test)
```
```{r}
myts <- ts(dji.log, frequency=30)
myts.train <- window(myts,end=150)
myts.test <- window(myts,start=150)

autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(myts.test, series="Test")

fc <- ets(myts.train)
future <- forecast::forecast(fc, h=20)
autoplot(future,h=100,include = 100)
checkresiduals(fc)
accuracy(future,myts.test)
```
```{r}
myts <- ts(spx.log, frequency=30)
myts.train <- window(myts,end=150)
myts.test <- window(myts,start=150)

autoplot(myts) +
  autolayer(myts.train, series="Training") +
  autolayer(myts.test, series="Test")

fc <- ets(myts.train)
future <- forecast::forecast(fc, h=20)
autoplot(future,h=100,include = 100)
checkresiduals(fc)
accuracy(future,myts.test)
```








```{r}
na.ts.ses<-ses(na.ts, h=100)
na.ts.holt<-holt(na.ts, h=100)
na.ts.sesd<-ses(na.ts,damped=TRUE, h=100)
na.ts.holtd<-holt(na.ts,damped=TRUE, h=100)
autoplot(na.ts.ses)
autoplot(na.ts.holt)
autoplot(na.ts.sesd)
autoplot(na.ts.holtd,include=200)
summary(na.ts.ses)
summary(na.ts.holt)
summary(na.ts.sesd)
summary(na.ts.holtd)
res.holtd<-residuals(na.ts.holtd)
test(res.holtd)
```
```{r}
na.ts.log<-log(na.ts)
autoplot(na.ts.log)
test(na.ts.log)
na.logd<-diff(na.ts.log)
autoplot(na.logd)
test(na.logd)
```

```{r}
na.arima<-auto.arima(na.ts.log)
autoplot(na.arima)
future <- forecast::forecast(na.arima, h=12)
autoplot(future,include=100)
```
```{r}
ets(dji.ts)
autoplot(forecast::forecast(ets(dji.ts)))
str(dji.ts)
head(dji.ts)

dji.ts.ses <- ses(dji.ts, h = 400)
autoplot(dji.ts.ses) +
  autolayer(dji.ts.ses$fitted)
dji.ts.ses$model
```




